services:
  postgres:
    image: postgres
    container_name: coursework_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: coursework
    ports:
      - "${POSTGRES_PORT:-5434}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - db-network

  postgres-test:
    image: postgres
    container_name: coursework_postgres_test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: coursework_test
    ports:
      - "${POSTGRES_TEST_PORT:-5435}:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - db-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coursework_app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/coursework?schema=public
      TEST_DATABASE_URL: postgresql://postgres:password123@postgres-test:5432/coursework_test?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - postgres-test
    networks:
      - db-network
    volumes:
      - ./prisma:/app/prisma

volumes:
  postgres_data:
    driver: local
  postgres_test_data:
    driver: local

networks:
  db-network:
    driver: bridge